#!/bin/sh
BACKUP_CONFIG=/etc/backup/config
BACKUP_PASSFILE=/etc/backup/passwd
BACKUP_DEST=/var/backup
BACKUP_FOLDERS=/etc\ /root\ /home

while [ -n "$1" ]
do
    [ "$1" = "-c" ] && shift && BACKUP_CONFIG=$1
    [ "$1" = "-i" ] && shift && BACKUP_INIT=1 && BORG_PASSPHRASE=$1
    shift
done

[ -f "$BACKUP_CONFIG" ] && . "$BACKUP_CONFIG"

[ -n "$BACKUP_OUTPUT" ] && exec > $BACKUP_OUTPUT 2>&1
if [ $EUID -ne 0 ]
then
    echo "`date`: Must be run as root"
    exit 1
fi

__cleanup()
{
    if [ -n "$BACKUP_MOUNTED" ]
    then
        umount $BACKUP_MOUNTPOINT
        echo "Backup location mounted"
        unset BACKUP_MOUNTED
    fi
}


echo "Beginning backup: `date`"

# Only do the following if backing up to a server
if [ -n "$BACKUP_SERVER" ]
then
    starttime=`date '+%s'`
    runningtime=0
    while [ $runningtime -le 120 ]
    do
        if ping -c 1 $BACKUP_SERVER > /dev/null 2>&1
        then
            connected=1
            break
        fi
        sleep 1
        runningtime=$((`date '+%s'` - $starttime))
    done

    if [ -n "$connected" ]
    then
        echo "$BACKUP_SERVER reachable. Proceeding."
    else
        echo "$BACKUP_SERVER NOT reachable. Exiting."
        echo "Ending backup: `date`"
        exit -1
    fi
fi

if [ -n "$BACKUP_MOUNTPOINT" ]
then
    if mount "$BACKUP_MOUNTPOINT" 2>&1
    then
        echo "Backup location successfully mounted"
        BACKUP_MOUNTED=1
    else
        echo "Backup location mount FAILED. Confirm entry in /etc/fstab."
        echo "Quitting."
        echo "Ending backup: `date`"
        exit -2
    fi
fi

if [ -n "$BACKUP_INIT" ]
then
    echo "$BORG_PASSPHRASE" > $BACKUP_PASSFILE
    borg init --encryption=authenticated "$BACKUP_DEST"
fi

BORG_PASSPHRASE=`cat $BACKUP_PASSFILE` borg create \
    $BACKUP_DEST::`date '+%Y%m%d'` \
    $BACKUP_FOLDERS 2>&1

__cleanup
echo "Ending backup: `date`"
